version: '3.7'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
  server:
    build: .
    ports:
      - '8000:8000'
    depends_on:
        - db